apiVersion: v1
kind: Service
metadata:
  name: freight-forecast
  labels:
    app: freight-forecast
spec:
  type: ClusterIP
  selector:
    app: freight-forecast
  ports:
    - name: http
      port: 80
      targetPort: 8000
